client_config_backend: settings
client_config:
  client_id: 202264815644.apps.googleusercontent.com
  client_secret: _insert_your_client_secret_here

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file